trigger:
- main 

pool:
  vmImage: 'ubuntu-latest'
  name: 'Default'

steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'AzureForStudentsConnection' 
    appName: 'mihirwebapp' 
    imageName: 'cosc1209registry.azurecr.io/webappserver'  
    tag: 'latest'  
